baseURL: "https://chihche-liew.github.io/" 
title: Zhizhe Liu
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildFuture: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: pubs/
          weight: 1
        - name: Work In Progress
          url: proj/
          weight: 2
        - name: Working Experience
          url: working/
          weight: 3
        - name: Teaching Experience
          url: teaching/
          weight: 4 
        - name: Research Toolkits
          url: repos/
          weight: 5

params:
    description: "This website hosts Zhizhe Liu's personal information and the scripts which could be commonly used in accounting research."
    author: Zhizhe Liu
    env: production
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["Publications","Work In Progress","Research Toolkits"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Zhizhe Liu
          subtitle: "@ Computer Sciences, UW-Madison"
          subtitle1: "Hi, I am a graduate student at Computer Sciences, UW-Madison, and a researcher with a strong focus on archival financial accounting. My research interest sits at corporate disclosure and information processing and their consequences in capital markets. "
          subtitle4: "There're also some pipelines, scripts and replication packages which may be useful to capital-market researchers in the 'Research Toolkits' part. Hope they will help!"
          imageUrl: "ZhizheLiuPage.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: pubs/
            - name: Work In Progress
              url: proj/
            - name: Working Experience
              url: working/
            - name: Teaching Experience
              url: teaching/
            - name: Research Toolkits
              url: repos/

    socialIcons:
        - name: CV
          url: Zhizhe_Liu_CV.pdf
        - name: Email
          url: mailto:zhizhe.liu@wisc.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=Eez1mkMAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/Chihche-Liew
        - name: LinkedIn
          url: https://www.linkedin.com/in/zhizhe-liu/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Zhizhe Liu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2